Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.1
  TargetRailsVersion: 4.2
  Exclude:
    - 'extras/**/*'
    - 'locale/**/*'
    - 'test/**/*'

# Just so it looks like core Foreman
Style/HashSyntax:
  EnforcedStyle: hash_rockets

Layout/DotPosition:
  EnforcedStyle: 'trailing'

Rails/ActionFilter:
  EnforcedStyle: action

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FormatStringToken:
  EnforcedStyle: template
